### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'find_all'

### ISSUE THREAD

**Issue by MadCreeper** [LovelyWei/EhMagnet#1]
![image](https://user-images.githubusercontent.com/33979935/61937474-836cb800-afc1-11e9-821f-c66c12cc28bc.png)

**Comment by aiyce** [comment]
![Snipaste_2019-07-26_16-30-42](https://user-images.githubusercontent.com/19799164/61938058-cd09d280-afc2-11e9-9684-622b1a980d8a.jpg)

**Comment by LovelyWei** [comment]
这个原因是之前是拉闸了.....
